### ISSUE TITLE
Voice parameters

### ISSUE THREAD

**Issue by vchulski** [charactr-platform/charactr-api-sdk-python#7]
Good day,

Is it planned to be added to the API opportunity to change voice parameters like speed or pitch?

**Comment by wiktor-mazur** [comment]
Hello!

Currently we are do not have this planned for development. However it is definitely a desirable feature and we will consider it in the upcoming discussions.

For now, you can utilize standard audio engineering algorithms to modify the speed or pitch in post-processing.

Thanks for your input and let me know if there's anything else I can help you with.

Best,
Wiktor

**Comment by vchulski** [comment]
Thanks for the quick and informative response. 

Do you have any recommendations/sources about how to modify the speed in post-processing? 

Best,
Vadim

**Comment by wiktor-mazur** [comment]
I can recommend you to try using ffmpeg.
